# Generated by Django 6.0 on 2026-03-04 00:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_orderitem_product_alter_product_collection_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='id',
            field=models.UUIDField(default=uuid.UUID('7f3f3be7-9b2a-4cae-a3db-4116c7a85a5c'), primary_key=True, serialize=False),
        ),
    ]
