# Generated by Django 6.0 on 2025-12-28 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0002_delete_likeditem'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagItemManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
